export const LOADING_REGISTER = 'LOADING_TO_REGISTR';
export const SUCCESS_REGISTER = 'SUCCESS_REGISTER';
export const ERROR_REGISTER = 'ERROR_REGISTER';

export const LOADING_LOGIN = 'LOADING_LOGIN';
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const ERROR_LOGIN = 'ERROR_LOGIN';

export const LOADING_LOGOUT = 'LOADING_LOGOUT';
export const SUCCESS_LOGOUT = 'SUCCESS_LOGOUT';
export const ERROR_LOGOUT= 'ERROR_LOGOUT';
