export const GET_NEWS = "GET_NEWS"
export const GET_NEWS_LOADING = "GET_NEWS_LOADING"
export const GET_NEWS_LOADED = "GET_NEWS_LOADED"
export const ERROR = "ERROR"
export const CLEAR_ERROR = "CLEAR_ERROR"